name: terragrunt
run-name: terragrunt-${{ inputs.action }}
on:
  workflow_dispatch:
    inputs:
      tgPath:
        type: string
        description: 'Terragrunt folder path'
        required: true
      action:
        type: choice
        description: 'Terragrunt action (Apply or Destroy)'
        required: true
        options:
        - apply
        - destroy
env:
  tf_version: '1.6.0'
  tg_version: '0.52.1'
  tf_working_dir: ${{ inputs.tgPath }}
jobs:
  plan:
    name: 'Terragrunt Plan'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4            
      - name: 'Terragrunt Plan'
        uses: gruntwork-io/terragrunt-action@v1
        with:
          tf_version: ${{ env.tf_version }}
          tg_version: ${{ env.tg_version }}
          tg_dir: ${{ env.tf_working_dir }}
          tg_command: 'plan'
        env:
          INPUT_PRE_EXEC_1:  |
            git config --global url."https://${{ github.repository_owner }}:${{ secrets.GITHUB_TOKEN }}@github.com/".insteadOf "https://github.com/"
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
  apply:
    needs: plan
    if: ${{ inputs.action == 'apply' }}
    name: 'Terragrunt Apply'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4            
      - name: 'Terragrunt Apply'
        uses: gruntwork-io/terragrunt-action@v1
        with:
          tf_version: ${{ env.tf_version }}
          tg_version: ${{ env.tg_version }}
          tg_dir: ${{ env.tf_working_dir }}
          tg_command: 'apply'
        env:
          INPUT_PRE_EXEC_1:  |
            git config --global url."https://${{ github.repository_owner }}:${{ secrets.GITHUB_TOKEN }}@github.com/".insteadOf "https://github.com/"
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
  destroy:
    needs: plan
    if: ${{ inputs.action == 'destroy' }}
    name: 'Terragrunt Destroy'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4            
      - name: 'Terragrunt Destroy'
        uses: gruntwork-io/terragrunt-action@v1
        with:
          tf_version: ${{ env.tf_version }}
          tg_version: ${{ env.tg_version }}
          tg_dir: ${{ env.tf_working_dir }}
          tg_command: 'destroy'
        env:
          INPUT_PRE_EXEC_1:  |
            git config --global url."https://${{ github.repository_owner }}:${{ secrets.GITHUB_TOKEN }}@github.com/".insteadOf "https://github.com/"
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}  