name: terragrunt-apply
run-name: terragrunt-apply
on:
  workflow_dispatch:
    inputs:
      tgPath:
        description: 'Terragrunt folder path'
        required: true
        type: string
env:
  tf_version: 'latest'
  tg_version: 'latest'
  tf_working_dir: ${{ inputs.tgPath }}
jobs:
  terragrunt:
    name: 'Terragrunt Apply'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4            
      - name: 'Terragrunt Init'
        uses: gruntwork-io/terragrunt-action@v1
        with:
          tf_version: ${{ env.tf_version }}
          tg_version: ${{ env.tg_version }}
          tg_dir: ${{ env.tf_working_dir }}
          tg_command: 'init'
        env:
          INPUT_PRE_EXEC_1:  |
            git config --global url."https://${{ github.repository_owner }}:${{ secrets.GITHUB_TOKEN }}@github.com/".insteadOf "https://github.com/"
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      - name: 'Terragrunt Plan'
        uses: the-commons-project/terragrunt-github-actions@master
        with:
          tf_version: ${{ env.tf_version }}
          tg_version: ${{ env.tg_version }}
          tg_dir: ${{ env.tf_working_dir }}
          tg_command: 'plan'
        env:
          INPUT_PRE_EXEC_1:  |
            git config --global url."https://${{ github.repository_owner }}:${{ secrets.GITHUB_TOKEN }}@github.com/".insteadOf "https://github.com/"
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      